### ISSUE TITLE
Úkoly 10.lekce

### ISSUE THREAD

**Issue by MartinaHytychova** [MartinaHytychova/Python_Django_training#11]
I když jsem si vše vytvořila a v administraci vytvořila i potřebná data, tak mi nejde zobrazit jednotlivá view a nejsem si jstá, kde mám chybu.

Mrkneš mi prosím na to? 

Děkuji.
:)

**Comment by pesikj** [comment]
Ahoj Martino,

soubor `pujcovna/urls.py` by měl vypadat takto - má tam být pouze odkaz na aplikaci, ne na jednotlivé pohledy.

```python
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('katalog/', include("katalog.urls")),
]
```

Dále soubor `katalog/urls.py` musí mít v sobě též seznam, nestačí mít adresy vypsané samostatně:

```python
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="katalog"),
    path("auto/", views.AutoView.as_view(), name="auto"),
    path("vypujcka/", views.VypujckaView.as_view(), name="vypujcka"),
    path("zakaznik/", views.ZakaznikView.as_view(), name="zakaznik"),
]
```

Dále složka `templates` by měla být v adresáři `katalog`, tj. uvnitř aplikace. Taky mám pocit, že nemáš zmigrovanou databázi, mně se ale po vygenerování migrací nepodařilo databázi zmigrovat. Možná ale jen nemáš nejnovější verzi v Gitu. Pokud bys s tím měla problémy, tak můžeš smazat soubor `db.sqlite3`, tím ale bohužel přijdeš o zadaná data.

**Comment by MartinaPiekna** [comment]
Ahá, chápu a praveno, moc děkuji. :) Funguje

**Comment by pesikj** [comment]
Super :-)
